name: flutter_course
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  #basics
  http: ^0.13.4
  path: ^1.8.0
  path_provider: ^2.0.5
  connectivity_plus: ^2.2.1
  uuid: ^3.0.4
  crypto: ^3.0.1
  shared_preferences: ^2.0.8 
  flutter_secure_storage: ^5.0.2
  secure_application: ^3.8.0
  safe_device: ^1.1.0
  lottie: ^1.2.1
  flutter_native_splash: ^2.0.1+1
  flutter_launcher_icons: ^0.9.2
  font_awesome_flutter: ^9.1.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  dio: ^4.0.0
  intl: ^0.17.0
  recase: ^4.0.0
  flutter_windowmanager: ^0.2.0
  fl_chart: ^0.45.0
  flutter_email_sender: ^5.1.0
  fancy_on_boarding: ^1.7.0
  dot_navigation_bar: ^1.0.1+3
  geolocator: ^8.2.0
  ndialog: ^4.1.0
  firebase_app_check: ^0.0.6+5
  flutter_recaptcha_v2:
     git:
      url: git://github.com/Clement549/flutter_recaptcha_v2
      ref: master
  #ui
  photo_view: ^0.13.0
  liquid_ui: ^1.0.0+9
  flutter_zoom_drawer: ^2.1.1
  overlay_support: ^1.2.1
  fluttertoast: ^8.0.8
  modal_bottom_sheet: ^2.0.0
  shimmer: ^2.0.0
  settings_ui: ^2.0.2
  numberpicker: ^2.1.1
  slide_to_act: ^2.0.1
  animations: ^2.0.2
  flutter_compass: ^0.7.0
  glassmorphism_ui: ^0.2.0
  shrink_sidemenu: ^2.0.0+2-null-safety
  #flutter_statusbar_manager: ^2.0.0
  #sliding_up_panel: ^2.0.0+1
  #rflutter_alert: ^2.0.4

  #firebase/ google
  firebase_storage: ^10.2.7
  firebase_core: ^1.12.0
  firebase_core_desktop: ^0.1.1-dev.3
  firebase_auth_desktop: ^0.1.1-dev.5
  firebase_crashlytics: ^2.5.1
  firebase_messaging: ^11.2.6
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.3.7
  #flutterfire_ui: ^0.3.4
  google_maps_flutter: ^2.1.1
  google_maps: ^6.0.0
  map_launcher: ^2.2.0
  url_launcher: ^6.0.20
  googleapis: ^8.0.0
  flutter_dialogs: ^2.1.1
  awesome_dialog: ^2.1.2
  loading_indicator: ^3.0.2
  #tools
  webview_flutter: ^3.0.0
  image_cropper: ^1.5.0
  image_picker: ^0.8.4+9
  flutter_image_compress: ^1.1.0
  file_picker: ^4.1.3
  #camera: ^0.9.4+1
  location: ^4.3.0
  flutter_polyline_points: ^1.0.0
  cached_network_image: ^3.1.0
  flutter_easyloading: ^3.0.3
  sn_progress_dialog: ^1.0.3
  package_info: ^2.0.2
  store_redirect: ^2.0.0
  flutter_vibrate: ^1.3.0
  in_app_review: ^2.0.3
  devicelocale: ^0.5.0
  open_mail_app: ^0.4.4
  gallery_saver: ^2.3.2
  local_auth: ^1.1.11
  share: ^2.0.4
  double_back_to_close_app: ^2.0.1
  open_file: ^3.2.1
  dropdown_search: ^2.0.0
  particles_flutter: ^0.1.4
  confetti: ^0.6.0
  #end


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

#flutter pub run flutter_launcher_icons:main
#flutter pub run flutter_native_splash:create

flutter_icons:
  image_path: "assets/dsa_icon.png"
  #image_path_ios: "assets/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/dsa_icon_foreground.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/dsa_logo_big.png"
  image_dark: "assets/dsa_logo_big.png"
  android: true
  ios: true
  #android_gravity: fill
  #ios_contenet_mode: scaleAspectFill


flutter:
  uses-material-design: true

  assets:
    - assets/
