# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'Firebase/AppCheck' # a tester si ca marche
  use_frameworks!

  # Pods for Runner

end
